### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by bmerry** [ska-sa/scikits.fitting#1]
When using `pip install -r requirements.txt` on a requirements file that includes scikits.fitting, installation fails if numpy is not already installed. I think the fix is to add a requirements.txt file for pip to find recursively.

**Comment by bmerry** [comment]
Correction: numpy needs to be listed as a setup_requires, and importing numpy.distutils.core should fail gracefully (I guess by falling back to setuptools setup). Also, `install_requires` is empty, and needs to list at least scipy.

**Comment by ludwigschwardt** [comment]
Indeed,

This package has not had much love in a while... Will gussy it up!

**Comment by ludwigschwardt** [comment]
Fixed in PR #3.
