### ISSUE TITLE
Warnings about loading deprecated matplotlib.delaunay

### ISSUE THREAD

**Issue by bmerry** [ska-sa/scikits.fitting#2]
With a default install of scifits.fitting+matplotlib, importing scikits.fitting gives this warning:

```
/home/bmerry/tmp/ve/local/lib/python2.7/site-packages/matplotlib/cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
```

It seems that using matplotlib.delaunay is only a fallback anyway, so possibly it should just be skipped? (and possibly scikits.delaunay added as a `install_requires` or `extras_require`)

**Comment by ludwigschwardt** [comment]
Fixed in PR #5.
